-- Base burrowed

-- =============================================
-- SCRIPT CORREGIDO PARA POSTGRESQL (ESCOM)
-- =============================================

-- 1. USUARIOS Y PERSONAL

CREATE TABLE Tecnico_Docente (
  id_tecnico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_empleado varchar UNIQUE NOT NULL,
  nombre varchar NOT NULL,
  apellido_pa varchar NOT NULL,
  apellido_ma varchar,
  correo varchar UNIQUE NOT NULL,
  turno varchar,
  contrasena varchar NOT NULL
);

CREATE TABLE Profesor (
  id_profesor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_empleado varchar UNIQUE NOT NULL,
  nombre varchar NOT NULL,
  apellido_pa varchar NOT NULL,
  apellido_ma varchar,
  correo_institucional varchar UNIQUE,
  contrasena varchar NOT NULL
);

CREATE TABLE Responsable_Lab (
  id_responsable INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar NOT NULL,
  apellido_pa varchar NOT NULL,
  apellido_ma varchar,
  correo varchar UNIQUE,
  contrasena varchar NOT NULL
);

-- 2. ACADEMIA

CREATE TABLE Laboratorio (
  id_laboratorio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_laboratorio varchar NOT NULL,
  ubicacion varchar,
  id_responsable integer REFERENCES Responsable_Lab(id_responsable),
  url_reglamento_pdf varchar
);

CREATE TABLE Materia (
  id_materia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_laboratorio integer REFERENCES Laboratorio(id_laboratorio),
  nombre_materia varchar NOT NULL,
  plan_estudios varchar
);

CREATE TABLE Practica (
  id_practica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_materia integer REFERENCES Materia(id_materia),
  numero_practica integer NOT NULL,
  nombre_practica varchar NOT NULL,
  objetivo text,
  duracion_estimada varchar,
  url_guia_pdf varchar
);

CREATE TABLE Grupo (
  id_grupo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_grupo varchar NOT NULL,
  semestre varchar NOT NULL,
  id_materia integer REFERENCES Materia(id_materia),
  id_profesor integer REFERENCES Profesor(id_profesor)
);

-- Índice único para evitar grupos duplicados
CREATE UNIQUE INDEX idx_grupo_unico ON Grupo (codigo_grupo, id_materia, semestre);

CREATE TABLE Horario_Clase (
  id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_grupo integer REFERENCES Grupo(id_grupo) ON DELETE CASCADE,
  dia_semana varchar NOT NULL,
  hora_inicio time NOT NULL,
  hora_fin time NOT NULL
);

-- Índice único para evitar choques de horario
CREATE UNIQUE INDEX idx_horario_choque ON Horario_Clase (id_grupo, dia_semana, hora_inicio);

-- 3. ALUMNOS

CREATE TABLE Alumno (
  id_alumno INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  boleta varchar UNIQUE NOT NULL,
  nombre varchar NOT NULL,
  apellido_pa varchar NOT NULL,
  apellido_ma varchar,
  correo_institucional varchar,
  correo_personal varchar,
  validado_por_profesor boolean DEFAULT false
);

CREATE TABLE Inscripcion_a_Grupo (
  id_grupo integer REFERENCES Grupo(id_grupo) ON DELETE CASCADE,
  id_alumno integer REFERENCES Alumno(id_alumno) ON DELETE CASCADE,
  PRIMARY KEY (id_grupo, id_alumno)
);

-- 4. MATERIALES

CREATE TABLE Material (
  id_material INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_laboratorio integer REFERENCES Laboratorio(id_laboratorio),
  nombre_material varchar NOT NULL,
  modelo varchar,
  proveedor varchar,
  no_serie varchar UNIQUE,
  estado_fisico varchar DEFAULT 'Bueno',
  estado_disponibilidad varchar DEFAULT 'Disponible',
  ubicacion_estante varchar,
  observaciones text,
  url_manual_pdf varchar,
  fecha_mantenimiento TIMESTAMP -- Corregido de datetime a TIMESTAMP
);

-- 5. SOLICITUDES

CREATE TABLE Solicitud (
  id_solicitud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_profesor integer REFERENCES Profesor(id_profesor),
  id_grupo integer REFERENCES Grupo(id_grupo),
  id_practica integer REFERENCES Practica(id_practica),
  id_tecnico_docente integer REFERENCES Tecnico_Docente(id_tecnico),
  fecha_solicitud TIMESTAMP DEFAULT NOW(), -- Corregido
  fecha_uso_programada TIMESTAMP NOT NULL, -- Corregido
  estado_solicitud varchar DEFAULT 'Pendiente',
  asistencia_docente boolean DEFAULT false
);

CREATE TABLE Detalle_Solicitud (
  id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_solicitud integer REFERENCES Solicitud(id_solicitud) ON DELETE CASCADE,
  id_material integer REFERENCES Material(id_material),
  cantidad_solicitada integer DEFAULT 1
);

CREATE TABLE Evaluacion_Tecnico_Docente (
  id_evaluacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_solicitud integer UNIQUE REFERENCES Solicitud(id_solicitud), -- Unique 1 a 1
  calificacion_atencion integer CHECK (calificacion_atencion BETWEEN 1 AND 5),
  entrega_material_completo boolean,
  comentarios text,
  fecha_evaluacion TIMESTAMP DEFAULT NOW()
);

CREATE TABLE Reporte_Incidencia (
  id_reporte INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_solicitud integer REFERENCES Solicitud(id_solicitud),
  id_material integer REFERENCES Material(id_material),
  tipo_incidencia varchar,
  descripcion text,
  fecha_reporte TIMESTAMP DEFAULT NOW()
);